/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models

import com.thebluealliance.models.APIStatusAppVersion

import com.squareup.moshi.Json

/**
 * 
 * @param currentSeason Year of the current FRC season.
 * @param maxSeason Maximum FRC season year for valid queries.
 * @param isDatafeedDown True if the entire FMS API provided by FIRST is down.
 * @param downEvents An array of strings containing event keys of any active events that are no longer updating.
 * @param ios 
 * @param android 
 */

data class APIStatus (
    /* Year of the current FRC season. */
    @Json(name = "current_season")
    val currentSeason: kotlin.Int,
    /* Maximum FRC season year for valid queries. */
    @Json(name = "max_season")
    val maxSeason: kotlin.Int,
    /* True if the entire FMS API provided by FIRST is down. */
    @Json(name = "is_datafeed_down")
    val isDatafeedDown: kotlin.Boolean,
    /* An array of strings containing event keys of any active events that are no longer updating. */
    @Json(name = "down_events")
    val downEvents: kotlin.collections.List<kotlin.String>,
    @Json(name = "ios")
    val ios: APIStatusAppVersion,
    @Json(name = "android")
    val android: APIStatusAppVersion
)

