/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models

import com.thebluealliance.models.WLTRecord

import com.squareup.moshi.Json

/**
 * 
 * @param playoffAverage 
 * @param level 
 * @param record 
 * @param currentLevelRecord 
 * @param status 
 */

data class EliminationAllianceStatus (
    @Json(name = "playoff_average")
    val playoffAverage: kotlin.Double? = null,
    @Json(name = "level")
    val level: kotlin.String? = null,
    @Json(name = "record")
    val record: WLTRecord? = null,
    @Json(name = "current_level_record")
    val currentLevelRecord: WLTRecord? = null,
    @Json(name = "status")
    val status: kotlin.String? = null
)

