/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * Insights for FIRST Stronghold qualification and elimination matches.
 * @param lowBar For the Low Bar - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param aChevalDeFrise For the Cheval De Frise - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param aPortcullis For the Portcullis - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param bRamparts For the Ramparts - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param bMoat For the Moat - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param cSallyPort For the Sally Port - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param cDrawbridge For the Drawbridge - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param dRoughTerrain For the Rough Terrain - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param dRockWall For the Rock Wall - An array with three values, number of times damaged, number of opportunities to damage, and percentage.
 * @param averageHighGoals Average number of high goals scored.
 * @param averageLowGoals Average number of low goals scored.
 * @param breaches An array with three values, number of times breached, number of opportunities to breach, and percentage.
 * @param scales An array with three values, number of times scaled, number of opportunities to scale, and percentage.
 * @param challenges An array with three values, number of times challenged, number of opportunities to challenge, and percentage.
 * @param captures An array with three values, number of times captured, number of opportunities to capture, and percentage.
 * @param averageWinScore Average winning score.
 * @param averageWinMargin Average margin of victory.
 * @param averageScore Average total score.
 * @param averageAutoScore Average autonomous score.
 * @param averageCrossingScore Average crossing score.
 * @param averageBoulderScore Average boulder score.
 * @param averageTowerScore Average tower score.
 * @param averageFoulScore Average foul score.
 * @param highScore An array with three values, high score, match key from the match with the high score, and the name of the match.
 */

data class EventInsights2016 (
    /* For the Low Bar - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "LowBar")
    val lowBar: kotlin.collections.List<kotlin.Float>,
    /* For the Cheval De Frise - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "A_ChevalDeFrise")
    val aChevalDeFrise: kotlin.collections.List<kotlin.Float>,
    /* For the Portcullis - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "A_Portcullis")
    val aPortcullis: kotlin.collections.List<kotlin.Float>,
    /* For the Ramparts - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "B_Ramparts")
    val bRamparts: kotlin.collections.List<kotlin.Float>,
    /* For the Moat - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "B_Moat")
    val bMoat: kotlin.collections.List<kotlin.Float>,
    /* For the Sally Port - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "C_SallyPort")
    val cSallyPort: kotlin.collections.List<kotlin.Float>,
    /* For the Drawbridge - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "C_Drawbridge")
    val cDrawbridge: kotlin.collections.List<kotlin.Float>,
    /* For the Rough Terrain - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "D_RoughTerrain")
    val dRoughTerrain: kotlin.collections.List<kotlin.Float>,
    /* For the Rock Wall - An array with three values, number of times damaged, number of opportunities to damage, and percentage. */
    @Json(name = "D_RockWall")
    val dRockWall: kotlin.collections.List<kotlin.Float>,
    /* Average number of high goals scored. */
    @Json(name = "average_high_goals")
    val averageHighGoals: kotlin.Float,
    /* Average number of low goals scored. */
    @Json(name = "average_low_goals")
    val averageLowGoals: kotlin.Float,
    /* An array with three values, number of times breached, number of opportunities to breach, and percentage. */
    @Json(name = "breaches")
    val breaches: kotlin.collections.List<kotlin.Float>,
    /* An array with three values, number of times scaled, number of opportunities to scale, and percentage. */
    @Json(name = "scales")
    val scales: kotlin.collections.List<kotlin.Float>,
    /* An array with three values, number of times challenged, number of opportunities to challenge, and percentage. */
    @Json(name = "challenges")
    val challenges: kotlin.collections.List<kotlin.Float>,
    /* An array with three values, number of times captured, number of opportunities to capture, and percentage. */
    @Json(name = "captures")
    val captures: kotlin.collections.List<kotlin.Float>,
    /* Average winning score. */
    @Json(name = "average_win_score")
    val averageWinScore: kotlin.Float,
    /* Average margin of victory. */
    @Json(name = "average_win_margin")
    val averageWinMargin: kotlin.Float,
    /* Average total score. */
    @Json(name = "average_score")
    val averageScore: kotlin.Float,
    /* Average autonomous score. */
    @Json(name = "average_auto_score")
    val averageAutoScore: kotlin.Float,
    /* Average crossing score. */
    @Json(name = "average_crossing_score")
    val averageCrossingScore: kotlin.Float,
    /* Average boulder score. */
    @Json(name = "average_boulder_score")
    val averageBoulderScore: kotlin.Float,
    /* Average tower score. */
    @Json(name = "average_tower_score")
    val averageTowerScore: kotlin.Float,
    /* Average foul score. */
    @Json(name = "average_foul_score")
    val averageFoulScore: kotlin.Float,
    /* An array with three values, high score, match key from the match with the high score, and the name of the match. */
    @Json(name = "high_score")
    val highScore: kotlin.collections.List<kotlin.String>
)

