/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models

import com.thebluealliance.models.EventRankingExtraStatsInfo
import com.thebluealliance.models.EventRankingRankings
import com.thebluealliance.models.EventRankingSortOrderInfo

import com.squareup.moshi.Json

/**
 * 
 * @param rankings List of rankings at the event.
 * @param sortOrderInfo List of year-specific values provided in the `sort_orders` array for each team.
 * @param extraStatsInfo List of special TBA-generated values provided in the `extra_stats` array for each item.
 */

data class EventRanking (
    /* List of rankings at the event. */
    @Json(name = "rankings")
    val rankings: kotlin.collections.List<EventRankingRankings>,
    /* List of year-specific values provided in the `sort_orders` array for each team. */
    @Json(name = "sort_order_info")
    val sortOrderInfo: kotlin.collections.List<EventRankingSortOrderInfo>,
    /* List of special TBA-generated values provided in the `extra_stats` array for each item. */
    @Json(name = "extra_stats_info")
    val extraStatsInfo: kotlin.collections.List<EventRankingExtraStatsInfo>? = null
)

