/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * 
 * @param autoPoints 
 * @param teleopPoints 
 * @param containerPoints 
 * @param totePoints 
 * @param litterPoints 
 * @param foulPoints 
 * @param adjustPoints 
 * @param totalPoints 
 * @param foulCount 
 * @param toteCountFar 
 * @param toteCountNear 
 * @param toteSet 
 * @param toteStack 
 * @param containerCountLevel1 
 * @param containerCountLevel2 
 * @param containerCountLevel3 
 * @param containerCountLevel4 
 * @param containerCountLevel5 
 * @param containerCountLevel6 
 * @param containerSet 
 * @param litterCountContainer 
 * @param litterCountLandfill 
 * @param litterCountUnprocessed 
 * @param robotSet 
 */

data class MatchScoreBreakdown2015Alliance (
    @Json(name = "auto_points")
    val autoPoints: kotlin.Int? = null,
    @Json(name = "teleop_points")
    val teleopPoints: kotlin.Int? = null,
    @Json(name = "container_points")
    val containerPoints: kotlin.Int? = null,
    @Json(name = "tote_points")
    val totePoints: kotlin.Int? = null,
    @Json(name = "litter_points")
    val litterPoints: kotlin.Int? = null,
    @Json(name = "foul_points")
    val foulPoints: kotlin.Int? = null,
    @Json(name = "adjust_points")
    val adjustPoints: kotlin.Int? = null,
    @Json(name = "total_points")
    val totalPoints: kotlin.Int? = null,
    @Json(name = "foul_count")
    val foulCount: kotlin.Int? = null,
    @Json(name = "tote_count_far")
    val toteCountFar: kotlin.Int? = null,
    @Json(name = "tote_count_near")
    val toteCountNear: kotlin.Int? = null,
    @Json(name = "tote_set")
    val toteSet: kotlin.Boolean? = null,
    @Json(name = "tote_stack")
    val toteStack: kotlin.Boolean? = null,
    @Json(name = "container_count_level1")
    val containerCountLevel1: kotlin.Int? = null,
    @Json(name = "container_count_level2")
    val containerCountLevel2: kotlin.Int? = null,
    @Json(name = "container_count_level3")
    val containerCountLevel3: kotlin.Int? = null,
    @Json(name = "container_count_level4")
    val containerCountLevel4: kotlin.Int? = null,
    @Json(name = "container_count_level5")
    val containerCountLevel5: kotlin.Int? = null,
    @Json(name = "container_count_level6")
    val containerCountLevel6: kotlin.Int? = null,
    @Json(name = "container_set")
    val containerSet: kotlin.Boolean? = null,
    @Json(name = "litter_count_container")
    val litterCountContainer: kotlin.Int? = null,
    @Json(name = "litter_count_landfill")
    val litterCountLandfill: kotlin.Int? = null,
    @Json(name = "litter_count_unprocessed")
    val litterCountUnprocessed: kotlin.Int? = null,
    @Json(name = "robot_set")
    val robotSet: kotlin.Boolean? = null
)

