/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * 
 * @param score Score for this alliance. Will be null or -1 for an unplayed match.
 * @param teamKeys 
 * @param surrogateTeamKeys TBA team keys (eg `frc254`) of any teams playing as a surrogate.
 * @param dqTeamKeys TBA team keys (eg `frc254`) of any disqualified teams.
 */

data class MatchAlliance (
    /* Score for this alliance. Will be null or -1 for an unplayed match. */
    @Json(name = "score")
    val score: kotlin.Int,
    @Json(name = "team_keys")
    val teamKeys: kotlin.collections.List<kotlin.String>,
    /* TBA team keys (eg `frc254`) of any teams playing as a surrogate. */
    @Json(name = "surrogate_team_keys")
    val surrogateTeamKeys: kotlin.collections.List<kotlin.String>? = null,
    /* TBA team keys (eg `frc254`) of any disqualified teams. */
    @Json(name = "dq_team_keys")
    val dqTeamKeys: kotlin.collections.List<kotlin.String>? = null
)

