/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models

import com.thebluealliance.models.MatchAlliance

import com.squareup.moshi.Json

/**
 * A list of alliances, the teams on the alliances, and their score.
 * @param red 
 * @param blue 
 */

data class MatchSimpleAlliances (
    @Json(name = "red")
    val red: MatchAlliance? = null,
    @Json(name = "blue")
    val blue: MatchAlliance? = null
)

