/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * 
 * @param autoPoints 
 * @param teleopPoints 
 * @param foulPoints 
 * @param adjustPoints 
 * @param totalPoints 
 * @param robot1Auto 
 * @param robot2Auto 
 * @param robot3Auto 
 * @param rotor1Auto 
 * @param rotor2Auto 
 * @param autoFuelLow 
 * @param autoFuelHigh 
 * @param autoMobilityPoints 
 * @param autoRotorPoints 
 * @param autoFuelPoints 
 * @param teleopFuelPoints 
 * @param teleopFuelLow 
 * @param teleopFuelHigh 
 * @param teleopRotorPoints 
 * @param kPaRankingPointAchieved 
 * @param teleopTakeoffPoints 
 * @param kPaBonusPoints 
 * @param rotorBonusPoints 
 * @param rotor1Engaged 
 * @param rotor2Engaged 
 * @param rotor3Engaged 
 * @param rotor4Engaged 
 * @param rotorRankingPointAchieved 
 * @param techFoulCount 
 * @param foulCount 
 * @param touchpadNear 
 * @param touchpadMiddle 
 * @param touchpadFar 
 */

data class MatchScoreBreakdown2017Alliance (
    @Json(name = "autoPoints")
    val autoPoints: kotlin.Int? = null,
    @Json(name = "teleopPoints")
    val teleopPoints: kotlin.Int? = null,
    @Json(name = "foulPoints")
    val foulPoints: kotlin.Int? = null,
    @Json(name = "adjustPoints")
    val adjustPoints: kotlin.Int? = null,
    @Json(name = "totalPoints")
    val totalPoints: kotlin.Int? = null,
    @Json(name = "robot1Auto")
    val robot1Auto: MatchScoreBreakdown2017Alliance.Robot1Auto? = null,
    @Json(name = "robot2Auto")
    val robot2Auto: MatchScoreBreakdown2017Alliance.Robot2Auto? = null,
    @Json(name = "robot3Auto")
    val robot3Auto: MatchScoreBreakdown2017Alliance.Robot3Auto? = null,
    @Json(name = "rotor1Auto")
    val rotor1Auto: kotlin.Boolean? = null,
    @Json(name = "rotor2Auto")
    val rotor2Auto: kotlin.Boolean? = null,
    @Json(name = "autoFuelLow")
    val autoFuelLow: kotlin.Int? = null,
    @Json(name = "autoFuelHigh")
    val autoFuelHigh: kotlin.Int? = null,
    @Json(name = "autoMobilityPoints")
    val autoMobilityPoints: kotlin.Int? = null,
    @Json(name = "autoRotorPoints")
    val autoRotorPoints: kotlin.Int? = null,
    @Json(name = "autoFuelPoints")
    val autoFuelPoints: kotlin.Int? = null,
    @Json(name = "teleopFuelPoints")
    val teleopFuelPoints: kotlin.Int? = null,
    @Json(name = "teleopFuelLow")
    val teleopFuelLow: kotlin.Int? = null,
    @Json(name = "teleopFuelHigh")
    val teleopFuelHigh: kotlin.Int? = null,
    @Json(name = "teleopRotorPoints")
    val teleopRotorPoints: kotlin.Int? = null,
    @Json(name = "kPaRankingPointAchieved")
    val kPaRankingPointAchieved: kotlin.Boolean? = null,
    @Json(name = "teleopTakeoffPoints")
    val teleopTakeoffPoints: kotlin.Int? = null,
    @Json(name = "kPaBonusPoints")
    val kPaBonusPoints: kotlin.Int? = null,
    @Json(name = "rotorBonusPoints")
    val rotorBonusPoints: kotlin.Int? = null,
    @Json(name = "rotor1Engaged")
    val rotor1Engaged: kotlin.Boolean? = null,
    @Json(name = "rotor2Engaged")
    val rotor2Engaged: kotlin.Boolean? = null,
    @Json(name = "rotor3Engaged")
    val rotor3Engaged: kotlin.Boolean? = null,
    @Json(name = "rotor4Engaged")
    val rotor4Engaged: kotlin.Boolean? = null,
    @Json(name = "rotorRankingPointAchieved")
    val rotorRankingPointAchieved: kotlin.Boolean? = null,
    @Json(name = "techFoulCount")
    val techFoulCount: kotlin.Int? = null,
    @Json(name = "foulCount")
    val foulCount: kotlin.Int? = null,
    @Json(name = "touchpadNear")
    val touchpadNear: kotlin.String? = null,
    @Json(name = "touchpadMiddle")
    val touchpadMiddle: kotlin.String? = null,
    @Json(name = "touchpadFar")
    val touchpadFar: kotlin.String? = null
) {

    /**
     * 
     * Values: unknown,mobility,none
     */
    enum class Robot1Auto(val value: kotlin.String) {
        @Json(name = "Unknown") unknown("Unknown"),
        @Json(name = "Mobility") mobility("Mobility"),
        @Json(name = "None") none("None");
    }
    /**
     * 
     * Values: unknown,mobility,none
     */
    enum class Robot2Auto(val value: kotlin.String) {
        @Json(name = "Unknown") unknown("Unknown"),
        @Json(name = "Mobility") mobility("Mobility"),
        @Json(name = "None") none("None");
    }
    /**
     * 
     * Values: unknown,mobility,none
     */
    enum class Robot3Auto(val value: kotlin.String) {
        @Json(name = "Unknown") unknown("Unknown"),
        @Json(name = "Mobility") mobility("Mobility"),
        @Json(name = "None") none("None");
    }
}

