/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models

import com.thebluealliance.models.TeamEventStatusAllianceBackup

import com.squareup.moshi.Json

/**
 * 
 * @param number Alliance number.
 * @param pick Order the team was picked in the alliance from 0-2, with 0 being alliance captain.
 * @param name Alliance name, may be null.
 * @param backup 
 */

data class TeamEventStatusAlliance (
    /* Alliance number. */
    @Json(name = "number")
    val number: kotlin.Int,
    /* Order the team was picked in the alliance from 0-2, with 0 being alliance captain. */
    @Json(name = "pick")
    val pick: kotlin.Int,
    /* Alliance name, may be null. */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "backup")
    val backup: TeamEventStatusAllianceBackup? = null
)

