/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * Backup status, may be null.
 * @param out TBA key for the team replaced by the backup.
 * @param `in` TBA key for the backup team called in.
 */

data class TeamEventStatusAllianceBackup (
    /* TBA key for the team replaced by the backup. */
    @Json(name = "out")
    val out: kotlin.String? = null,
    /* TBA key for the backup team called in. */
    @Json(name = "in")
    val `in`: kotlin.String? = null
)

