/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * 
 * @param year Year this robot competed in.
 * @param robotName Name of the robot as provided by the team.
 * @param key Internal TBA identifier for this robot.
 * @param teamKey TBA team key for this robot.
 */

data class TeamRobot (
    /* Year this robot competed in. */
    @Json(name = "year")
    val year: kotlin.Int,
    /* Name of the robot as provided by the team. */
    @Json(name = "robot_name")
    val robotName: kotlin.String,
    /* Internal TBA identifier for this robot. */
    @Json(name = "key")
    val key: kotlin.String,
    /* TBA team key for this robot. */
    @Json(name = "team_key")
    val teamKey: kotlin.String
)

