/**
* The Blue Alliance API v3
* # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.
*
* The version of the OpenAPI document: 3.8.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.thebluealliance.models


import com.squareup.moshi.Json

/**
 * 
 * @param type Type of webcast, typically descriptive of the streaming provider.
 * @param channel Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe.
 * @param date The date for the webcast in `yyyy-mm-dd` format. May be null.
 * @param file File identification as may be required for some types. May be null.
 */

data class Webcast (
    /* Type of webcast, typically descriptive of the streaming provider. */
    @Json(name = "type")
    val type: Webcast.Type,
    /* Type specific channel information. May be the YouTube stream, or Twitch channel name. In the case of iframe types, contains HTML to embed the stream in an HTML iframe. */
    @Json(name = "channel")
    val channel: kotlin.String,
    /* The date for the webcast in `yyyy-mm-dd` format. May be null. */
    @Json(name = "date")
    val date: kotlin.String? = null,
    /* File identification as may be required for some types. May be null. */
    @Json(name = "file")
    val file: kotlin.String? = null
) {

    /**
     * Type of webcast, typically descriptive of the streaming provider.
     * Values: youtube,twitch,ustream,iframe,html5,rtmp,livestream,directLink,mms,justin,stemtv,dacast
     */
    enum class Type(val value: kotlin.String) {
        @Json(name = "youtube") youtube("youtube"),
        @Json(name = "twitch") twitch("twitch"),
        @Json(name = "ustream") ustream("ustream"),
        @Json(name = "iframe") iframe("iframe"),
        @Json(name = "html5") html5("html5"),
        @Json(name = "rtmp") rtmp("rtmp"),
        @Json(name = "livestream") livestream("livestream"),
        @Json(name = "direct_link") directLink("direct_link"),
        @Json(name = "mms") mms("mms"),
        @Json(name = "justin") justin("justin"),
        @Json(name = "stemtv") stemtv("stemtv"),
        @Json(name = "dacast") dacast("dacast");
    }
}

